export type Lang = "ru" | "bg" | "en" | "ua";

export type Tour = {
  id: number;
  date: string;
  departure_time: string;
  arrival_time: string;
  price: number;
  seats: number | { free: number };
  layout_variant?: string | null;
};

export type Step = 1 | 2 | 3;

export type Dict = {
  noResults: string;
  outbound: string;
  inbound: string;
  outboundShort: string;
  inboundShort: string;
  pick: string;
  chosen: string;
  freeSeats: (n: number) => string;
  book: string;
  buy: string;
  paid: string;
  canceled: string;
  pay: string;
  cancel: string;
  errSearch: string;
  errAction: string;
  loading: string;
  inRoute: string;
  departure: string;
  arrival: string;
  price: string;
  total: string;
  adults: string;
  discounted: string;
  ticketTitle: string;
  ticketNumber: string;
  ticketActionPurchase: string;
  ticketActionBook: string;
  ticketCreated: string;
  ticketStatus: string;
  ticketStatusPaid: string;
  ticketStatusPending: string;
  ticketStatusCanceled: string;
  ticketTotal: string;
  ticketContacts: string;
  ticketPassengers: string;
  ticketPassengerSeat: string;
  ticketPassengerSeatReturn: string;
  ticketPassengerBaggage: string;
  ticketPassengerBaggageReturn: string;
  ticketYes: string;
  ticketNo: string;
  ticketDownload: string;
  ticketOutbound: string;
  ticketReturn: string;
  ticketOpenOnline: string;
  ticketDownloadReady: string;
  ticketDownloadDismiss: string;
  contactsDescription: string;
  contactsAndPayment: string;
  contactsPhone: string;
  contactsEmail: string;
  baggageIncludedTitle: string;
  baggageIncludedCabin: string;
  baggageIncludedChecked: string;
  baggageIncludedNote: string;
  extraBaggagePrice: string;
  addExtraBaggage: string;
  addedExtraBaggage: string;
  removeExtraBaggage: string;
  step1Title: string;
  step2Title: string;
  step3Title: string;
  step1ShortLabel: string;
  step2ShortLabel: string;
  step3ShortLabel: string;
  step1SummaryChoose: string;
  step2SummaryChooseSeats: string;
  step2SummaryFillNames: string;
  step2SummaryReady: string;
  step3SummaryEmpty: string;
  step3SummaryPending: string;
  step3SummaryPaid: string;
  step3SummaryCanceled: string;
  next: string;
  subtotal: string;
  stepLabel: (step: number) => string;
  stepCounter: (current: number, total: number) => string;
  changeOutbound: string;
  changeReturn: string;
  outboundNotSelected: string;
  orderSummaryTitle: string;
  orderSummaryNote: string;
  liveLabel: string;
  seatsLabel: string;
  seatsPending: string;
  seatsSelected: (seats: number[]) => string;
  seatSelectionTitle: string;
  seatSelectionSubtitle: string;
  openSeatPicker: string;
  changeSeatPicker: string;
  selectedSeatsLabel: (selected: number, total: number) => string;
  seatSummarySingle: (seat: number) => string;
  seatSummaryMultiple: (count: number, seats: number[]) => string;
  passengersTitle: string;
  passengersHint: string;
  passengerPlaceholder: string;
  errorSelectSeat: string;
  errorFillName: string;
  passengerLabel: (index: number) => string;
  extraBaggageHeading: string;
  configureBaggage: string;
  pricePerBagLabel: string;
  baggageToggleHide: string;
  baggageIncludedBadge: string;
  baggageCollapsedHint: string;
  addBagAria: string;
  removeBagAria: string;
};
